/*
Copyright AppsCode Inc. and Contributors

Licensed under the AppsCode Community License 1.0.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://github.com/appscode/licenses/raw/1.0.0/AppsCode-Community-1.0.0.md

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by Kubeform. DO NOT EDIT.

package main

import (
	jsoniter "github.com/json-iterator/go"
	"k8s.io/apimachinery/pkg/runtime/schema"
	alertv1alpha1 "kubeform.dev/provider-wavefront-api/apis/alert/v1alpha1"
	cloudv1alpha1 "kubeform.dev/provider-wavefront-api/apis/cloud/v1alpha1"
	dashboardv1alpha1 "kubeform.dev/provider-wavefront-api/apis/dashboard/v1alpha1"
	derivedv1alpha1 "kubeform.dev/provider-wavefront-api/apis/derived/v1alpha1"
	externalv1alpha1 "kubeform.dev/provider-wavefront-api/apis/external/v1alpha1"
	ingestionv1alpha1 "kubeform.dev/provider-wavefront-api/apis/ingestion/v1alpha1"
	maintenancev1alpha1 "kubeform.dev/provider-wavefront-api/apis/maintenance/v1alpha1"
	rolev1alpha1 "kubeform.dev/provider-wavefront-api/apis/role/v1alpha1"
	servicev1alpha1 "kubeform.dev/provider-wavefront-api/apis/service/v1alpha1"
	userv1alpha1 "kubeform.dev/provider-wavefront-api/apis/user/v1alpha1"
	"kubeform.dev/provider-wavefront-controller/controllers"
)

type Data struct {
	JsonIt       jsoniter.API
	ResourceType string
}

var allJsonIt = map[schema.GroupVersionResource]Data{
	{
		Group:    "alert.wavefront.kubeform.com",
		Version:  "v1alpha1",
		Resource: "alerts",
	}: {
		JsonIt:       controllers.GetJSONItr(alertv1alpha1.GetEncoder(), alertv1alpha1.GetDecoder()),
		ResourceType: "wavefront_alert",
	},
	{
		Group:    "alert.wavefront.kubeform.com",
		Version:  "v1alpha1",
		Resource: "targets",
	}: {
		JsonIt:       controllers.GetJSONItr(alertv1alpha1.GetEncoder(), alertv1alpha1.GetDecoder()),
		ResourceType: "wavefront_alert_target",
	},
	{
		Group:    "cloud.wavefront.kubeform.com",
		Version:  "v1alpha1",
		Resource: "integrationappdynamics",
	}: {
		JsonIt:       controllers.GetJSONItr(cloudv1alpha1.GetEncoder(), cloudv1alpha1.GetDecoder()),
		ResourceType: "wavefront_cloud_integration_app_dynamics",
	},
	{
		Group:    "cloud.wavefront.kubeform.com",
		Version:  "v1alpha1",
		Resource: "integrationawsexternalids",
	}: {
		JsonIt:       controllers.GetJSONItr(cloudv1alpha1.GetEncoder(), cloudv1alpha1.GetDecoder()),
		ResourceType: "wavefront_cloud_integration_aws_external_id",
	},
	{
		Group:    "cloud.wavefront.kubeform.com",
		Version:  "v1alpha1",
		Resource: "integrationazures",
	}: {
		JsonIt:       controllers.GetJSONItr(cloudv1alpha1.GetEncoder(), cloudv1alpha1.GetDecoder()),
		ResourceType: "wavefront_cloud_integration_azure",
	},
	{
		Group:    "cloud.wavefront.kubeform.com",
		Version:  "v1alpha1",
		Resource: "integrationazureactivitylogs",
	}: {
		JsonIt:       controllers.GetJSONItr(cloudv1alpha1.GetEncoder(), cloudv1alpha1.GetDecoder()),
		ResourceType: "wavefront_cloud_integration_azure_activity_log",
	},
	{
		Group:    "cloud.wavefront.kubeform.com",
		Version:  "v1alpha1",
		Resource: "integrationcloudtrails",
	}: {
		JsonIt:       controllers.GetJSONItr(cloudv1alpha1.GetEncoder(), cloudv1alpha1.GetDecoder()),
		ResourceType: "wavefront_cloud_integration_cloudtrail",
	},
	{
		Group:    "cloud.wavefront.kubeform.com",
		Version:  "v1alpha1",
		Resource: "integrationcloudwatches",
	}: {
		JsonIt:       controllers.GetJSONItr(cloudv1alpha1.GetEncoder(), cloudv1alpha1.GetDecoder()),
		ResourceType: "wavefront_cloud_integration_cloudwatch",
	},
	{
		Group:    "cloud.wavefront.kubeform.com",
		Version:  "v1alpha1",
		Resource: "integrationec2s",
	}: {
		JsonIt:       controllers.GetJSONItr(cloudv1alpha1.GetEncoder(), cloudv1alpha1.GetDecoder()),
		ResourceType: "wavefront_cloud_integration_ec2",
	},
	{
		Group:    "cloud.wavefront.kubeform.com",
		Version:  "v1alpha1",
		Resource: "integrationgcps",
	}: {
		JsonIt:       controllers.GetJSONItr(cloudv1alpha1.GetEncoder(), cloudv1alpha1.GetDecoder()),
		ResourceType: "wavefront_cloud_integration_gcp",
	},
	{
		Group:    "cloud.wavefront.kubeform.com",
		Version:  "v1alpha1",
		Resource: "integrationgcpbillings",
	}: {
		JsonIt:       controllers.GetJSONItr(cloudv1alpha1.GetEncoder(), cloudv1alpha1.GetDecoder()),
		ResourceType: "wavefront_cloud_integration_gcp_billing",
	},
	{
		Group:    "cloud.wavefront.kubeform.com",
		Version:  "v1alpha1",
		Resource: "integrationnewrelics",
	}: {
		JsonIt:       controllers.GetJSONItr(cloudv1alpha1.GetEncoder(), cloudv1alpha1.GetDecoder()),
		ResourceType: "wavefront_cloud_integration_newrelic",
	},
	{
		Group:    "cloud.wavefront.kubeform.com",
		Version:  "v1alpha1",
		Resource: "integrationteslas",
	}: {
		JsonIt:       controllers.GetJSONItr(cloudv1alpha1.GetEncoder(), cloudv1alpha1.GetDecoder()),
		ResourceType: "wavefront_cloud_integration_tesla",
	},
	{
		Group:    "dashboard.wavefront.kubeform.com",
		Version:  "v1alpha1",
		Resource: "dashboards",
	}: {
		JsonIt:       controllers.GetJSONItr(dashboardv1alpha1.GetEncoder(), dashboardv1alpha1.GetDecoder()),
		ResourceType: "wavefront_dashboard",
	},
	{
		Group:    "dashboard.wavefront.kubeform.com",
		Version:  "v1alpha1",
		Resource: "jsons",
	}: {
		JsonIt:       controllers.GetJSONItr(dashboardv1alpha1.GetEncoder(), dashboardv1alpha1.GetDecoder()),
		ResourceType: "wavefront_dashboard_json",
	},
	{
		Group:    "derived.wavefront.kubeform.com",
		Version:  "v1alpha1",
		Resource: "metrics",
	}: {
		JsonIt:       controllers.GetJSONItr(derivedv1alpha1.GetEncoder(), derivedv1alpha1.GetDecoder()),
		ResourceType: "wavefront_derived_metric",
	},
	{
		Group:    "external.wavefront.kubeform.com",
		Version:  "v1alpha1",
		Resource: "links",
	}: {
		JsonIt:       controllers.GetJSONItr(externalv1alpha1.GetEncoder(), externalv1alpha1.GetDecoder()),
		ResourceType: "wavefront_external_link",
	},
	{
		Group:    "ingestion.wavefront.kubeform.com",
		Version:  "v1alpha1",
		Resource: "policies",
	}: {
		JsonIt:       controllers.GetJSONItr(ingestionv1alpha1.GetEncoder(), ingestionv1alpha1.GetDecoder()),
		ResourceType: "wavefront_ingestion_policy",
	},
	{
		Group:    "maintenance.wavefront.kubeform.com",
		Version:  "v1alpha1",
		Resource: "windows",
	}: {
		JsonIt:       controllers.GetJSONItr(maintenancev1alpha1.GetEncoder(), maintenancev1alpha1.GetDecoder()),
		ResourceType: "wavefront_maintenance_window",
	},
	{
		Group:    "role.wavefront.kubeform.com",
		Version:  "v1alpha1",
		Resource: "roles",
	}: {
		JsonIt:       controllers.GetJSONItr(rolev1alpha1.GetEncoder(), rolev1alpha1.GetDecoder()),
		ResourceType: "wavefront_role",
	},
	{
		Group:    "service.wavefront.kubeform.com",
		Version:  "v1alpha1",
		Resource: "accounts",
	}: {
		JsonIt:       controllers.GetJSONItr(servicev1alpha1.GetEncoder(), servicev1alpha1.GetDecoder()),
		ResourceType: "wavefront_service_account",
	},
	{
		Group:    "user.wavefront.kubeform.com",
		Version:  "v1alpha1",
		Resource: "users",
	}: {
		JsonIt:       controllers.GetJSONItr(userv1alpha1.GetEncoder(), userv1alpha1.GetDecoder()),
		ResourceType: "wavefront_user",
	},
	{
		Group:    "user.wavefront.kubeform.com",
		Version:  "v1alpha1",
		Resource: "groups",
	}: {
		JsonIt:       controllers.GetJSONItr(userv1alpha1.GetEncoder(), userv1alpha1.GetDecoder()),
		ResourceType: "wavefront_user_group",
	},
}

func getJsonItAndResType(gvr schema.GroupVersionResource) Data {
	return allJsonIt[gvr]
}
